module.exports = {
  apps: [
    {
      name: 'aescion-api',
      script: 'npm',
      args: 'run start:prod',
      cwd: './',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      error_file: './logs/api-error.log',
      out_file: './logs/api-out.log',
      merge_logs: true,
    },
    {
      name: 'aescion-admin',
      script: 'npm',
      args: 'start',
      cwd: '../Frontend/admin',
      instances: 1,
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      error_file: '../Frontend/admin/logs/admin-error.log',
      out_file: '../Frontend/admin/logs/admin-out.log',
      merge_logs: true,
    },
    {
      name: 'aescion-website',
      script: 'npm',
      args: 'start',
      cwd: '../Frontend/website',
      instances: 'max',
      exec_mode: 'cluster',
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
      },
      log_date_format: 'YYYY-MM-DD HH:mm Z',
      error_file: '../Frontend/website/logs/website-error.log',
      out_file: '../Frontend/website/logs/website-out.log',
      merge_logs: true,
    }
  ],
};
